export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_CATEGORIES = "SET_CURRENT_CATEGORIES";
export const SET_CURRENT_SERVICES = "SET_CURRENT_SERVICES";
export const SET_CURRENT_MY_SERVICES = "SET_CURRENT_MY_SERVICES";